application:
  # dev开发环境 test测试环境 prod线上环境 *
  mode: dev
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 服务名称 *
  name: go-guns
  # 端口号 *
  port: 8000
  # 数据权限功能开关
  enabledp: false
logger:
  # 日志存放路径 *
  path: temp/admin/logs
jwt:
  # token 密钥，生产环境时及的修改
  secret: go-guns
  # token 过期时间 单位：秒
  timeout: 2592000
# 数据库配置
database:
  driver: mysql
  source: root:123456@tcp(127.0.0.1:3306)/go_guns?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
gen:
  # 代码生成读取的数据库名称
  dbname: go_guns
  # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
  frontpath: C:/Users/a2437/Desktop/FrontCode/go-guns-ui/src
